### ISSUE TITLE
Release 1.0.0 GA

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dotnet-xamarin#37]
This issue serves to track the GA release of this library.

- [x] Target .NET 3.0.0, [follow this issue](https://github.com/getsentry/sentry-dotnet/issues/723).
- [x] Sentry Wizard https://github.com/getsentry/sentry-docs/pull/2809
- [x] Merge Docs https://github.com/getsentry/sentry-docs/pull/2909

**Comment by lucas-zimerman** [comment]
@bruno-garcia  could you clarify what are those Docs?

**Comment by bruno-garcia** [comment]
The docs are go here:

https://github.com/getsentry/sentry-docs/blob/master/src/platforms/dotnet/guides/xamarin/index.mdx
And you need a config file: https://github.com/getsentry/sentry-docs/blob/master/src/platforms/dotnet/guides/xamarin/config.yml

Similar to:
https://github.com/getsentry/sentry-docs/blob/master/src/platforms/dotnet/guides/wpf/index.mdx
https://github.com/getsentry/sentry-docs/blob/master/src/platforms/dotnet/guides/wpf/config.yml

A Wizard (which you did already, might need updating now that you have two packages) to show in Sentry when a user creates a project. Basically a file called `xamarin.md` similar to this `wpf.md` here:

https://github.com/getsentry/sentry-docs/blob/master/src/wizard/dotnet/wpf.md

**Comment by lucas-zimerman** [comment]
Thanks! I'll update the Wizard and after that, I'll make the Docs.

**Comment by bruno-garcia** [comment]
@lucas-zimerman worth noting at the end of the docs that line numbers are not yet available in release builds

**Comment by bruno-garcia** [comment]
@lucas-zimerman we can maybe append the standard `exception.ToString()` into a Context so folks can use `mono-symbolicate`? Then we document how to do that?

**Comment by lucas-zimerman** [comment]
Added Docs PR.
